instrument_labels = { # This dictionary maps instrument keys to their human-readable labels (KEY, VALUE)
    "piano": "Piano",
    "guitar": "Guitar",
    "violin": "Violin",
    "viola": "Viola",
    "cello": "Cello",
    "uprightBass": "Upright Bass",
    "flute": "Flute",
    "clarinet": "Clarinet",
    "oboe": "Oboe",
    "bassoon": "Bassoon",
    "sopSax": "Soprano Saxophone",
    "altoSax": "Alto Saxophone",
    "tenSax": "Tenor Saxophone",
    "barSax": "Baritone Saxophone",
    "trumpet": "Trumpet",
    "trombone": "Trombone",
    "frenchHorn": "French Horn",
    "tuba": "Tuba",
    "harp": "Harp",
    "drums": "Drums",
    "voice": "Voice",
    "other": "Other"
}
